CoverMe/Models/NotificationRequest.cs
using System;

namespace CoverMe.Models
{
    public class NotificationRequest
    {
        public int Id { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public TimeSpan TimeToSend { get; set; }
        public float Latitude { get; set; }
        public float Longitude { get; set; }
        public int RainThreshold { get; set; }
    }
}

CoverMe/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace CoverMe.Controllers
{
    public class HomeController : Controller
    {
        public HomeController() {}

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View();
        }
    }
}

CoverMe/Controllers/LocationController.cs
using CoverMe.Data.Models;
using CoverMe.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace CoverMe.Controllers
{
    public class LocationController : Controller
    {
        private readonly ILocationService LocationService;
        public LocationController(ILocationService locationService)
        {
            LocationService = locationService;
        }

        public async Task<IEnumerable<Location>> Search(string query)
        {
            return await LocationService.Search(query);
        }
    }
}

CoverMe/Controllers/NotificationController.cs
using CoverMe.Data.Extensions;
using CoverMe.Data.Models;
using CoverMe.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace CoverMe.Controllers
{
    public class NotificationController : Controller
    {
        private readonly INotificationService NotificationService;
        private readonly ILocationService LocationService;

        public NotificationController(INotificationService notificationService, ILocationService locationService)
        {
            NotificationService = notificationService;
            LocationService = locationService;
        }

        [HttpPost]
        public async Task<IActionResult> RegisterForNotifications(NotificationRequestBody requestBody)
        {
            // Load the timezone for the selected location
            var timeZone = await LocationService.GetTimeZone(requestBody.Latitude, requestBody.Longitude);

            // Parse the request body into the correct model
            var notificationRequest = requestBody.ToNotificationRequest(timeZone);

            try
            {
                await NotificationService.AddNotificationRequest(notificationRequest);
            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }

            return Ok();
        }

        [HttpPost]
        public async Task<IActionResult> Unsubscribe(UnsubscribeRequest request)
        {
            await NotificationService.Unsubscribe(request);

            return Ok();
        }
    }
}

CoverMe/Controllers/UnsubscribeController.cs
using Microsoft.AspNetCore.Mvc;

namespace CoverMe.Controllers
{
    public class UnsubscribeController : Controller
    {
        public UnsubscribeController() { }

        public IActionResult Index()
        {
            return View();
        }
    }
}

CoverMe/Pages/FetchData.cshtml
@page "/fetchdata"
@inject HttpClient Http

<h1>Weather forecast</h1>

<p>This component demonstrates fetching data from the server.</p>

@if (forecasts == null)
{
    <p><em>Loading...</em></p>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Temp. (C)</th>
                <th>Temp. (F)</th>
                <th>Summary</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var forecast in forecasts)
            {
                <tr>
                    <td>@forecast.Date.ToShortDateString()</td>
                    <td>@forecast.TemperatureC</td>
                    <td>@forecast.TemperatureF</td>
                    <td>@forecast.Summary</td>
                </tr>
            }
        </tbody>
    </table>
}

@functions {
    WeatherForecast[] forecasts;

    protected override async Task OnInitAsync()
    {
        forecasts = await Http.GetJsonAsync<WeatherForecast[]>("sample-data/weather.json");
    }

    class WeatherForecast
    {
        public DateTime Date { get; set; }
        public int TemperatureC { get; set; }
        public int TemperatureF { get; set; }
        public string Summary { get; set; }
    }
}

CoverMe/Pages/Index.cshtml
@page "/"

<h1>Hello, world!</h1>

Welcome to your new app.

<SurveyPrompt Title="How is Blazor working for you?" />

CoverMe/Views/Home/Index.cshtml
@model IEnumerable<TimeZoneInfo>

@{
    ViewData["Title"] = "- Home";
}


<!--Include CDN links for Select2 -->
<link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />
<link href="https://cdn.jsdelivr.net/npm/select2-bootstrap-theme@0.1.0-beta.10/dist/select2-bootstrap.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/js/select2.full.min.js"></script>

<!--International Telephone Input Scripts-->
<link href="~/lib/intl-tel-input/css/intlTelInput.min.css" rel="stylesheet" />
<script src="~/lib/intl-tel-input/js/intlTelInput.min.js"></script>


<div class="text-center">
    <h1><span class="oi oi-rain"></span> CoverMe</h1>
    <h5>Never be surprised by precipitation again.</h5>
</div>

<div class="row">
    <div class="col-sm-6 offset-sm-3 text-center">
        <small>
            A simple service that alerts you when you should bring an umbrella with you.
            Register below using either your e-mail address or phone number, select a location, time, and precipitation threshold.
            Once you sign up you'll receive notifications on days when there is a chance of precipitation greater than your selected threshold.
        </small>
    </div>
</div>

<div class="row mt-2">
    <form class="col-sm-6 offset-sm-3" onsubmit="onClickSignUp(event)">
        <div class="form-group">
            <label for="inputEmailAddress">Email Address</label>
            <input type="email" class="form-control" id="inputEmailAddress" />
        </div>
        <div class="col-sm-2 offset-sm-5 text-center">or</div>
        <div class="form-group">
            <label for="inputPhoneNumber">Phone Number</label>
            <input type="tel" class="form-control" id="inputPhoneNumber" />
        </div>
        <div class="form-group">
            <label for="inputLocation">Select a Location</label>
            <select class="address-search form-control select2-single" style="width: 100%;" id="inputLocation" required></select>
        </div>
        <div class="form-group">
            <label for="inputTime">Notification Time</label>
            <input type="time" class="form-control" id="inputTime" required />
        </div>
        <div class="form-group">
            <label for="inputRainThreshold">Precipitation Minimum Percentage <small>(Number between 0 and 100)</small></label>
            <input type="number" max="100" min="0" class="form-control" id="inputRainThreshold" required />
        </div>
        <div class="form-group">
            <button type="submit" class="form-control btn-info" id="signUpButton">Sign Up</button>
        </div>
        <div class="form-group text-center">
            <small><u><a asp-controller="Unsubscribe" asp-action="Index">Click Here to Unsubscribe</a></u></small>
        </div>
    </form>
</div>


<script>
    // Initialize phone input
    var phoneInput = document.querySelector("#inputPhoneNumber");
    var iti = window.intlTelInput(phoneInput, {
        utilsScript: "lib/intl-tel-input/js/utils.js",
    });

    $(document).ready(function () {
        $('.address-search').select2({
            theme: 'bootstrap',
            width: 'resolve',
            ajax: {
                delay: 250, // Wait before sending the request
                url: '/Location/Search',
                dataType: 'json',
                data: function (params) {
                    return {
                        query: params.term
                    };
                },
                processResults: function (data) {
                    return {
                        results: data
                    };
                }
            },
            placeHolder: 'Search for an address to use',
            minimumInputLength: 3,
            templateResult: formatLocation,
            templateSelection: formatLocationSelection
        });
    });

    function formatLocation(location) {
        if (location.loading) {
            return location.text;
        }

        return location.fullAddress;
    }

    function formatLocationSelection(location) {
        return location.fullAddress;
    }

    function onClickSignUp(event) {
        // Prevent the default onSubmit event
        event.preventDefault();

        // Disable the sign up button to prevent spamming
        $("#signUpButton").prop("disabled", true);
        $('#signUpButton').text('Processing...');

        const location = $("#inputLocation").val().split(";");

        $.post("Notification/RegisterForNotifications",
            {
                requestBody: {
                    phoneNumber: iti.getNumber(intlTelInputUtils.numberFormat.E164),
                    phoneNumberCountryCode: iti.getSelectedCountryData()["iso2"],
                    emailAddress: $("#inputEmailAddress").val(),
                    latitude: location[0],
                    longitude: location[1],
                    timeToSend: $("#inputTime").val(),
                    rainThreshold: $("#inputRainThreshold").val(),
                }
            })
            .done(function () {
                new Toast({
                    message: "Notification request successfully submitted!",
                    type: "success",
                });
            })
            .fail(function () {
                // TODO return error message from api instead of generic one
                new Toast({
                    message: "Something went wrong. Please try again.",
                    type: "danger",
                });
            })
            .always(function () {
                // Reset the sign up button after a failure or a success
                $("#signUpButton").prop("disabled", false);
                $('#signUpButton').text('Sign Up');
            });;
    }
</script>

CoverMe/Views/Home/Unsubscribe.cshtml
@model IEnumerable<TimeZoneInfo>

@{
    ViewData["Title"] = "- Unsubscribe";
}

<!--International Telephone Input Scripts-->
<link href="~/lib/intl-tel-input/css/intlTelInput.min.css" rel="stylesheet" />
<script src="~/lib/intl-tel-input/js/intlTelInput.min.js"></script>

<div class="text-center">
    <h1><span class="oi oi-rain"></span> CoverMe</h1>
</div>

<div class="row">
    <div class="col-sm-6 offset-sm-3 text-center">
        <small>
            We're sorry to see you go!
            Just enter your email or phone number where you receive our notifications and we'll remove you immediately.
        </small>
    </div>
</div>

<div class="row mt-2">
    <form class="col-sm-6 offset-sm-3" onsubmit="onClickUnsubscribe(event)">
        <div class="form-group">
            <label for="inputEmailAddress">Email Address</label>
            <input type="email" class="form-control" id="inputEmailAddress" />
        </div>
        <div class="col-sm-2 offset-sm-5 text-center">or</div>
        <div class="form-group">
            <label for="inputPhoneNumber">Phone Number</label>
            <input type="tel" class="form-control" id="inputPhoneNumber" />
        </div>
        <div class="form-group">
            <button type="submit" class="form-control btn-info" id="unsubscribeButton">Unsubscribe</button>
        </div>
        <div class="col-sm-6 offset-sm-3 text-center">
            <small><u><a asp-controller="Home" asp-action="Index">Return Home</a></u></small>
        </div>
    </form>
</div>


<script>
    // Initialize phone input
    var phoneInput = document.querySelector("#inputPhoneNumber");
    var iti = window.intlTelInput(phoneInput, {
        utilsScript: "/lib/intl-tel-input/js/utils.js",
    });

    function onClickUnsubscribe(event) {
        // Prevent the default onSubmit event
        event.preventDefault();

        // Disable the sign up button to prevent spamming
        $("#unsubscribeButton").prop("disabled", true);

        $.post("/Notification/Unsubscribe",
            {
                request: {
                    phoneNumber: iti.getNumber(intlTelInputUtils.numberFormat.E164),
                    phoneNumberCountryCode: iti.getSelectedCountryData()["iso2"],
                    emailAddress: $("#inputEmailAddress").val(),
                }
            })
            .done(function () {
                new Toast({
                    message: "Successfully unsubscribed!",
                    type: "success",
                });
            })
            .fail(function () {
                new Toast({
                    message: "Something went wrong. Please try again.",
                    type: "danger",
                });
            }) 
            .always(function () {
                $("#unsubscribeButton").prop("disabled", false);
            });;
    }
</script>

CoverMe/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>CoverMe @(ViewData["Title"])</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/open-iconic/font/css/open-iconic-bootstrap.css">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/toast-js/Toast.min.css" />
</head>
<body>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/toast-js/Toast.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

    <div class="container">
        <main role="main" class="pb-3 mt-5">
            @RenderBody()
        </main>
    </div>
</body>
</html>

CoverMe/Views/Unsubscribe/Index.cshtml
@model IEnumerable<TimeZoneInfo>

@{
    ViewData["Title"] = "- Unsubscribe";
}

<!--International Telephone Input Scripts-->
<link href="~/lib/intl-tel-input/css/intlTelInput.min.css" rel="stylesheet" />
<script src="~/lib/intl-tel-input/js/intlTelInput.min.js"></script>

<div class="text-center">
    <h1><span class="oi oi-rain"></span> CoverMe</h1>
</div>

<div class="row">
    <div class="col-sm-6 offset-sm-3 text-center">
        <small>
            We're sorry to see you go!
            Just enter your email or phone number where you receive our notifications and we'll remove you immediately.
        </small>
    </div>
</div>

<div class="row mt-2">
    <form class="col-sm-6 offset-sm-3" onsubmit="onClickUnsubscribe(event)">
        <div class="form-group">
            <label for="inputEmailAddress">Email Address</label>
            <input type="email" class="form-control" id="inputEmailAddress" />
        </div>
        <div class="col-sm-2 offset-sm-5 text-center">or</div>
        <div class="form-group">
            <label for="inputPhoneNumber">Phone Number</label>
            <input type="tel" class="form-control" id="inputPhoneNumber" />
        </div>
        <div class="form-group">
            <button type="submit" class="form-control btn-info" id="unsubscribeButton">Unsubscribe</button>
        </div>
        <div class="col-sm-6 offset-sm-3 text-center">
            <small><u><a asp-controller="Home" asp-action="Index">Return Home</a></u></small>
        </div>
    </form>
</div>


<script>
    // Initialize phone input
    var phoneInput = document.querySelector("#inputPhoneNumber");
    var iti = window.intlTelInput(phoneInput, {
        utilsScript: "/lib/intl-tel-input/js/utils.js",
    });

    function onClickUnsubscribe(event) {
        // Prevent the default onSubmit event
        event.preventDefault();

        // Disable the sign up button to prevent spamming
        $("#unsubscribeButton").prop("disabled", true);

        $.post("/Notification/Unsubscribe",
            {
                request: {
                    phoneNumber: iti.getNumber(intlTelInputUtils.numberFormat.E164),
                    phoneNumberCountryCode: iti.getSelectedCountryData()["iso2"],
                    emailAddress: $("#inputEmailAddress").val(),
                }
            })
            .done(function () {
                new Toast({
                    message: "Successfully unsubscribed!",
                    type: "success",
                });
            })
            .fail(function () {
                new Toast({
                    message: "Something went wrong. Please try again.",
                    type: "danger",
                });
            }) 
            .always(function () {
                $("#unsubscribeButton").prop("disabled", false);
            });;
    }
</script>